package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	"github.com/leeliwei930/notion_cms/api/models"
	"github.com/leeliwei930/notion_cms/api/resource"
)

// Education is the resolver for the education field.
func (r *queryResolver) Education(ctx context.Context) ([]*models.EducationPathway, error) {
	return resource.GetEducationPathwayResource()
}

// Milestones is the resolver for the milestones field.
func (r *queryResolver) Milestones(ctx context.Context) ([]*models.Milestone, error) {
	return resource.GetMilestonesExperiencesResource()
}

// Website is the resolver for the website field.
func (r *queryResolver) Website(ctx context.Context) (*models.PageConfiguration, error) {
	return resource.GetDefaultPageResource()
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
