package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	"github.com/leeliwei930/notion_cms/api/resource"
	"github.com/leeliwei930/notion_cms/graph/model"
)

// EducationPathway is the resolver for the educationPathway field.
func (r *queryResolver) EducationPathway(ctx context.Context) ([]*model.EducationPathway, error) {
	educationPathways, err := resource.GetEducationPathwayResource()
	mappedEducationPathways := []*model.EducationPathway{}

	for _, education := range educationPathways {
		mappedEducationPathways = append(mappedEducationPathways, &model.EducationPathway{
			Title:         education.Title,
			InstituteName: education.InstituteName,
			StudyArea:     education.StudyArea,
			Icon:          education.Icon,
			Image:         education.Image,
			Location:      education.Location,
			CommencedOn:   education.CommencedOn,
			CompletedOn:   education.CompletedOn,
		})
	}

	return mappedEducationPathways, err

}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
