package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	"github.com/leeliwei930/notion_cms/api/models"
	"github.com/leeliwei930/notion_cms/api/resource"
)

// EducationPathway is the resolver for the educationPathway field.
func (r *queryResolver) EducationPathway(ctx context.Context) ([]models.EducationPathway, error) {
	return resource.GetEducationPathwayResource()
}

// WebsiteConfig is the resolver for the websiteConfig field.
func (r *queryResolver) WebsiteConfig(ctx context.Context) (*models.PageConfiguration, error) {
	return resource.GetDefaultPageResource()
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
