// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type EducationPathway struct {
	Title         string     `json:"title"`
	InstituteName string     `json:"instituteName"`
	StudyArea     string     `json:"studyArea"`
	Icon          string     `json:"icon"`
	Image         string     `json:"image"`
	Location      string     `json:"location"`
	CommencedOn   *time.Time `json:"commencedOn"`
	CompletedOn   *time.Time `json:"completedOn"`
}
